world: world
lobby: 0.5, 50, 0.5
name: Онион

leaderboard:
  enabled: true
  location: -3, 56, -19
  rotation: 0, 305, 0
  scale: 2.3

parkour:
  enabled: true
  sign: -24, 70, -10

#Количество игроков на каждом острове
islandPlayers: 1

#Дополнительные сундуки на отдельных островах с базовым лутом
basicChests:
  - 32, 50, 23

#Сунудки в центре карты, в которых будет дорогой лут
middleChests:
  - 23, 43, 45

#Точки спавна, где люди будут появляться через 30 минут после начала игры (DeathMatch)
deathmatchSpawns:
  - 0, 50, 0

#Мистический сундук с охуенным лутом
mysteryChest: 423, 34, 74

#Спекторасы будут появляться на этой высоте
respawnY: 64

islands:
  -
    spawn: 50.5, 64, 50.5
    chests:
      - 40, 60, 50
      - 42, 59, 53
